apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: compulsory-salmon-elk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: compulsory-salmon-elk 
  name: compulsory-salmon-elk
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: compulsory-salmon-elk
    weight: 100 
