apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: compulsory-salmon-elk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: compulsory-salmon-elk 
  name: compulsory-salmon-elk
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: compulsory-salmon-elk 
